"""Data source registry and adapters."""

from odds_analyzer.sources.api_football import (
    ApiFootballMatchNews,
    ApiFootballNewsBatch,
    ConfirmedLineup,
    PlayerAbsence,
    TeamNews,
    fetch_evening_api_football_news,
)

from odds_analyzer.sources.football_data import (
    COMPETITION_CODES,
    FootballDataFixture,
    FootballDataForm,
    FootballDataSnapshot,
    FootballDataStanding,
    fetch_evening_football_data,
    fetch_evening_fixtures,
    fixture_dashboard_id,
    parse_football_data_fixtures,
    parse_football_data_forms,
    parse_football_data_standing_forms,
    parse_football_data_standings,
)
from odds_analyzer.sources.odds_api import (
    LEAGUE_SPORT_KEYS,
    OddsApiEvent,
    fetch_evening_odds_api_events,
    fetch_odds_api_events,
    parse_odds_api_events,
)
from odds_analyzer.sources.polymarket import (
    MIN_SIGNAL_VOLUME,
    PolymarketEvent,
    PolymarketSpread,
    fetch_evening_polymarket_events,
    fetch_polymarket_events_for_date,
    parse_polymarket_events,
)
from odds_analyzer.sources.registry import (
    DataSourceCandidate,
    DataSourcePurpose,
    ReliabilityTier,
    get_data_source_candidates,
    get_sources_by_purpose,
)
from odds_analyzer.sources.sporttery import (
    SportteryMarket,
    SportteryMatch,
    SportteryOutcome,
    fetch_official_sporttery_matches,
    parse_official_sporttery,
)
from odds_analyzer.sources.weather import (
    WeatherBatch,
    WeatherSnapshot,
    fetch_fixture_weather,
    team_city_query,
    weather_description,
)

__all__ = [
    "ApiFootballMatchNews",
    "ApiFootballNewsBatch",
    "ConfirmedLineup",
    "COMPETITION_CODES",
    "DataSourceCandidate",
    "DataSourcePurpose",
    "FootballDataFixture",
    "FootballDataForm",
    "FootballDataSnapshot",
    "FootballDataStanding",
    "LEAGUE_SPORT_KEYS",
    "MIN_SIGNAL_VOLUME",
    "OddsApiEvent",
    "PolymarketEvent",
    "PolymarketSpread",
    "PlayerAbsence",
    "ReliabilityTier",
    "SportteryMarket",
    "SportteryMatch",
    "SportteryOutcome",
    "TeamNews",
    "WeatherBatch",
    "WeatherSnapshot",
    "fetch_evening_api_football_news",
    "fetch_evening_football_data",
    "fetch_evening_fixtures",
    "fetch_evening_odds_api_events",
    "fetch_evening_polymarket_events",
    "fetch_polymarket_events_for_date",
    "fetch_odds_api_events",
    "fetch_official_sporttery_matches",
    "fetch_fixture_weather",
    "fixture_dashboard_id",
    "get_data_source_candidates",
    "get_sources_by_purpose",
    "parse_football_data_fixtures",
    "parse_football_data_forms",
    "parse_football_data_standing_forms",
    "parse_football_data_standings",
    "parse_odds_api_events",
    "parse_polymarket_events",
    "parse_official_sporttery",
    "team_city_query",
    "weather_description",
]
